"""Add default data

Revision ID: fcb06a7b2cc3
Revises: 131fa37150ed
Create Date: 2023-06-26 11:07:15.886301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb06a7b2cc3'
down_revision = '131fa37150ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
